AWSTemplateFormatVersion: '2010-09-09'
Description: 'This template deploys a basic stuff to get the aws account set up'
Parameters:
  S3ArtifactStore:
    Type: String
    Description: Name of S3 bucket

Resources:

  # Common Lambda Role
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "lam-integration-test-role"
      Description: "Role assigned to lambdas"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: lam-integration-test-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource: '*'

  # Lambda
  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "lam-integration-test"
      Description: "lam-integration"
      Code: ./
      Handler: lambda.handler
      Runtime: python3.8
      Timeout: 60
      Role: !GetAtt LambdaRole.Arn
      PackageType: Zip
      MemorySize: 128
