AWSTemplateFormatVersion: '2010-09-09'
Description: 'This template deploys a basic stuff to get the aws account set up'
Parameters:
  S3ArtifactStore:
    Type: String
    Description: Name of S3 bucket

Resources:

  # Common Lambda Role
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "lam-integration-lambda-role"
      Description: "Role assigned to lambdas"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: lam-integration-s3-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:ListBucket'
                  - 's3:GetBucketPolicy'
                Resource: 
                  - !Join ['',['arn:aws:s3:::', !Ref S3ArtifactStore, '']]
                  - !Join ['',['arn:aws:s3:::', !Ref S3ArtifactStore, '/*']]
        - PolicyName: lam-integration-ec2-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'ec2:CreateNetworkInterface'
                  - 'ec2:DescribeNetworkInterfaces'
                  - 'ec2:DescribeVpcs'
                  - 'ec2:CreateTags'
                  - 'ec2:DeleteNetworkInterface'
                  - 'ec2:DescribeSubnets'
                  - 'ec2:DescribeSecurityGroups'
                  - 'ec2:AttachNetworkInterface'
                Resource: '*'

  # Lambda
  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      #VpcConfig:
        #SecurityGroupIds:
          #- sg-01cc1b2ae3c352d4f
        #SubnetIds:
          #- subnet-0f467d2099ef9a1ba
          #- subnet-0233a571f4e3de8d5
      Architectures:
        - arm64
      FunctionName: "lam-integration"
      Description: "lam-integration"
      Code: ./
      Handler: main.handler
      Runtime: python3.8
      Timeout: 60
      Role: !GetAtt LambdaRole.Arn
      PackageType: Zip
      MemorySize: 128
      Layers:
        - arn:aws:lambda:ap-south-1:690379282706:layer:lam-integration:1
